// nav
export const NAV__RESET_TO_MAIN = 'Nav/RESET_TO_MAIN';
export const NAV__RESET_TO_SIGN_IN = 'Nav/RESET_TO_SIGN_IN';

// app
export const APP__LOAD_RESOURCES = 'App/LOAD_RESOURCES';
export const APP__LOAD_RESOURCES_STARTED = 'App/LOAD_RESOURCES_STARTED';
export const APP__LOAD_RESOURCES_SUCCESS = 'App/LOAD_RESOURCES_SUCCESS';
export const APP__LOAD_RESOURCES_ERROR = 'App/LOAD_RESOURCES_ERROR';

